---
alt_send_esc: false

font:
  normal:
    family: MesloLGM Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: MesloLGM Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: MesloLGM Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: MesloLGM Nerd Font
    style: Bold Italic

  # Point size
  size: 13.0

window:
  startup_mode: Maximized
  padding:
    x: 6
    y: 6
  opacity: 0.95

schemes:
  breeze: &breeze
    # Default colors
    primary:
      background: '#232627'
      foreground: '#fcfcfc'

      dim_foreground: '#eff0f1'
      bright_foreground: '#ffffff'
      dim_background: '#31363b'
      bright_background: '#000000'

    # Normal colors
    normal:
      black: '#232627'
      red: '#ed1515'
      green: '#11d116'
      yellow: '#f67400'
      blue: '#1d99f3'
      magenta: '#9b59b6'
      cyan: '#1abc9c'
      white: '#fcfcfc'

    # Bright colors
    bright:
      black: '#7f8c8d'
      red: '#c0392b'
      green: '#1cdc9a'
      yellow: '#fdbc4b'
      blue: '#3daee9'
      magenta: '#8e44ad'
      cyan: '#16a085'
      white: '#ffffff'

    # Dim colors
    dim:
      black: '#31363b'
      red: '#783228'
      green: '#17a262'
      yellow: '#b65619'
      blue: '#1b668f'
      magenta: '#614a73'
      cyan: '#186c60'
      white: '#63686d'

  darcula: &darcula
    # Default colors
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xcaa9fa'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'

    # Bright colors
    bright:
      black:   '0x282a35'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'

  flat_remix: &flat_remix
    primary:
      background: '0x272a34'
      foreground: '0xFFFFFF'

    normal:
      black:   '0x1F2229'
      red:     '0xEC0101'
      green:   '0x47D4B9'
      yellow:  '0xFF8A18'
      blue:    '0x277FFF'
      magenta: '0xD71655'
      cyan:    '0x05A1F7'
      white:   '0xFFFFFF'


    bright:
      black:   '0x1F2229'
      red:     '0xD41919'
      green:   '0x5EBDAB'
      yellow:  '0xFEA44C'
      blue:    '0x367bf0'
      magenta: '0xBF2E5D'
      cyan:    '0x49AEE6'
      white:   '0xFFFFFF'

  iterm: &iterm
    # Default colors
    primary:
      background: '0x101421'
      foreground: '0xfffbf6'

    # Normal colors
    normal:
      black:   '0x2e2e2e'
      red:     '0xeb4129'
      green:   '0xabe047'
      yellow:  '0xf6c744'
      blue:    '0x47a0f3'
      magenta: '0x7b5cb0'
      cyan:    '0x64dbed'
      white:   '0xe5e9f0'

    # Bright colors
    bright:
      black:   '0x565656'
      red:     '0xec5357'
      green:   '0xc0e17d'
      yellow:  '0xf9da6a'
      blue:    '0x49a4f8'
      magenta: '0xa47de9'
      cyan:    '0x99faf2'
      white:   '0xffffff'

  nord: &nord
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'

colors: *nord
